# Generated by Django 6.0.6 on 2026-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.TextField()),
                ('years_experience', models.IntegerField(default=0)),
                ('projects_completed', models.IntegerField(default=0)),
                ('hero_image', models.ImageField(upload_to='hero/')),
            ],
        ),
    ]
