# Generated by Django 6.0.6 on 2026-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_aboutsection_about_image_alter_blogpost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroprofile',
            name='resume_url',
            field=models.URLField(blank=True),
        ),
    ]
