# Generated by Django 6.0.6 on 2026-06-21 07:42

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_heroprofile_resume_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='about_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='heroprofile',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='hero/'),
        ),
    ]
